-- Create suppliers table for procurement module
CREATE TABLE IF NOT EXISTS `suppliers` (
  `id` varchar(64) NOT NULL PRIMARY KEY,
  `supplierNumber` varchar(50) NOT NULL UNIQUE,
  `companyName` varchar(255) NOT NULL,
  `registrationNumber` varchar(100) UNIQUE,
  `taxId` varchar(100) UNIQUE,
  `contactPerson` varchar(255),
  `contactTitle` varchar(100),
  `email` varchar(320),
  `phone` varchar(50),
  `alternatePhone` varchar(50),
  `website` varchar(255),
  `address` text,
  `city` varchar(100),
  `country` varchar(100),
  `postalCode` varchar(20),
  `bankName` varchar(255),
  `bankBranch` varchar(255),
  `accountNumber` varchar(100),
  `accountName` varchar(255),
  `paymentTerms` varchar(100),
  `paymentMethods` varchar(255),
  `categories` varchar(500),
  `qualificationStatus` enum('pending', 'pre_qualified', 'qualified', 'rejected', 'inactive') NOT NULL DEFAULT 'pending',
  `qualificationDate` datetime,
  `certifications` varchar(500),
  `qualityRating` int(11) DEFAULT 0,
  `deliveryRating` int(11) DEFAULT 0,
  `priceCompetitiveness` int(11) DEFAULT 0,
  `averageRating` int(11) DEFAULT 0,
  `totalOrders` int(11) DEFAULT 0,
  `totalSpent` int(11) DEFAULT 0,
  `lastOrderDate` datetime,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `notes` text,
  `createdBy` varchar(64),
  `createdAt` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `supplier_company_idx` (`companyName`),
  KEY `supplier_status_idx` (`qualificationStatus`),
  KEY `supplier_rating_idx` (`averageRating`),
  KEY `supplier_active_idx` (`isActive`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
